# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('post', '0003_auto_20171110_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.Assignment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='submit_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.SubmitAssignment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
