# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submitassignment',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
